version: 2

build:
  os: ubuntu-lts-latest
  tools:
    python: "3.10"

python:
  install:
    # equivalent to: pip install .[all]
    - method: pip
      path: .
      extra_requirements:
        - all
    # equivalent to: pip install .[docs]
    - method: pip
      path: .
      extra_requirements:
        - docs

formats: all
