# Generated by cstruct-stubgen
from typing import BinaryIO, TypeAlias, overload

import dissect.cstruct as __cs__

class _c_obfuscate(__cs__.cstruct):
    class ObfuscationType(__cs__.Enum):
        OBFUSCATION_NONE = ...
        OBFUSCATION_XOR = ...
        OBFUSCATION_RC4 = ...
        OBFUSCATION_BASE64 = ...
        OBFUSCATION_LZNT1 = ...

    class StageEvasionSettingsV1(__cs__.Structure):
        copy_pe_header: _c_obfuscate.uint16
        eaf_bypass: _c_obfuscate.uint16
        rdll_use_syscalls: _c_obfuscate.uint16
        max_size: _c_obfuscate.uint32
        payload_size: _c_obfuscate.uint32
        @overload
        def __init__(
            self,
            copy_pe_header: _c_obfuscate.uint16 | None = ...,
            eaf_bypass: _c_obfuscate.uint16 | None = ...,
            rdll_use_syscalls: _c_obfuscate.uint16 | None = ...,
            max_size: _c_obfuscate.uint32 | None = ...,
            payload_size: _c_obfuscate.uint32 | None = ...,
        ): ...
        @overload
        def __init__(self, fh: bytes | memoryview | bytearray | BinaryIO, /): ...

    class StageEvasionSettingsV2(__cs__.Structure):
        copy_pe_header: _c_obfuscate.uint16
        eaf_bypass: _c_obfuscate.uint16
        rdll_use_syscalls: _c_obfuscate.uint16
        rdll_use_driploading: _c_obfuscate.uint16
        rdll_dripload_delay: _c_obfuscate.uint32
        max_size: _c_obfuscate.uint32
        payload_size: _c_obfuscate.uint32
        @overload
        def __init__(
            self,
            copy_pe_header: _c_obfuscate.uint16 | None = ...,
            eaf_bypass: _c_obfuscate.uint16 | None = ...,
            rdll_use_syscalls: _c_obfuscate.uint16 | None = ...,
            rdll_use_driploading: _c_obfuscate.uint16 | None = ...,
            rdll_dripload_delay: _c_obfuscate.uint32 | None = ...,
            max_size: _c_obfuscate.uint32 | None = ...,
            payload_size: _c_obfuscate.uint32 | None = ...,
        ): ...
        @overload
        def __init__(self, fh: bytes | memoryview | bytearray | BinaryIO, /): ...

    class StageObfuscateSettings(__cs__.Structure):
        obfuscation_type: _c_obfuscate.ObfuscationType
        key_size: _c_obfuscate.uint32
        original_size: _c_obfuscate.uint32
        payload_size: _c_obfuscate.uint32
        @overload
        def __init__(
            self,
            obfuscation_type: _c_obfuscate.ObfuscationType | None = ...,
            key_size: _c_obfuscate.uint32 | None = ...,
            original_size: _c_obfuscate.uint32 | None = ...,
            payload_size: _c_obfuscate.uint32 | None = ...,
        ): ...
        @overload
        def __init__(self, fh: bytes | memoryview | bytearray | BinaryIO, /): ...

# Technically `c_obfuscate` is an instance of `_c_obfuscate`, but then we can't use it in type hints
c_obfuscate: TypeAlias = _c_obfuscate
